name: Update events

on:
  schedule:
    - cron: '0 8,12,16,20,22,23 * * *'
  push:
    branches:
    - master

permissions: write-all

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true
      - name: Fetch events
        run: go run main.go
      - uses: peter-evans/create-pull-request@v6
        id: cpr
        with:
          title: 'Update events'
          commit-message: |
            🤖 update events using rebot.
          delete-branch: true

      - name: Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase
